namespace Mead.MusicBee.Enums;

public enum SettingId
{
    CompactPlayerFlickrEnabled = 1,
    FileTaggingPreserveModificationTime = 2,
    LastDownloadFolder = 3,
    ArtistGenresOnly = 4,
    IgnoreNamePrefixes = 5,
    IgnoreNameChars = 6,
    PlayCountTriggerPercent = 7,
    PlayCountTriggerSeconds = 8,
    SkipCountTriggerPercent = 9,
    SkipCountTriggerSeconds = 10,
    CustomWebLinkName1 = 11,
    CustomWebLinkName2 = 12,
    CustomWebLinkName3 = 13,
    CustomWebLinkName4 = 14,
    CustomWebLinkName5 = 15,
    CustomWebLinkName6 = 16,
    CustomWebLinkName7 = 29,
    CustomWebLinkName8 = 30,
    CustomWebLinkName9 = 31,
    CustomWebLinkName10 = 32,
    CustomWebLink1 = 17,
    CustomWebLink2 = 18,
    CustomWebLink3 = 19,
    CustomWebLink4 = 20,
    CustomWebLink5 = 21,
    CustomWebLink6 = 22,
    CustomWebLink7 = 33,
    CustomWebLink8 = 34,
    CustomWebLink9 = 35,
    CustomWebLink10 = 36,
    CustomWebLinkNowPlaying1 = 23,
    CustomWebLinkNowPlaying2 = 24,
    CustomWebLinkNowPlaying3 = 25,
    CustomWebLinkNowPlaying4 = 26,
    CustomWebLinkNowPlaying5 = 27,
    CustomWebLinkNowPlaying6 = 28,
    CustomWebLinkNowPlaying7 = 37,
    CustomWebLinkNowPlaying8 = 38,
    CustomWebLinkNowPlaying9 = 39,
    CustomWebLinkNowPlaying10 = 40
}