name: "[Mead.MusicBee] Create nuget release"

on:
  push:
    tags:
      - release/Mead.MusicBee/*

jobs:
  build:
    uses: ./.github/workflows/CreateNugetRelease.yml
    with:
      project-name: Mead.MusicBee
