name: "[Mead.MusicBee.Api] Create release"

on:
  push:
    tags:
      - release/Mead.MusicBee.Api/*

jobs:
  build:
    permissions:
      contents: write
    
    uses: ./.github/workflows/CreateRelease.yml
    with:
      project-name: Mead.MusicBee.Api
    secrets:
      nuget-api-key: ${{ secrets.NUGET_API_KEY }}
